/**
This code was generated by THE SPARKLING EVENTUAL CONSISTENT UNICORNS
Do not touch or risk the wrath of the ECUs
This Command was generated from DSL.json
*/
using Acme.Command;
namespace Acme.Command.RemoveProductFromCart {public class RemoveProductFromCart: Command {public String customerId {get; private set;}
public String cartId {get; private set;}}}