/**
This code was generated by THE SPARKLING EVENTUAL CONSISTENT UNICORNS
Do not touch or risk the wrath of the ECUs
This Command was generated from DSL.json
*/
using Acme.Commands;
namespace Acme.Commands.RemoveProductFromCart {public class RemoveProductFromCart: Command {public string customerId {get; private set;}
public string cartId {get; private set;}}}