/**
This code was generated by THE SPARKLING EVENTUAL CONSISTENT UNICORNS
Do not touch or risk the wrath of the ECUs
This Event was generated from DSL.json
*/
using Acme.Events;
namespace Acme.Events {public class CustomerPlacedOrder: Event {public string customerId {get;}
public string orderId {get;}
public string cartId {get;}public CustomerPlacedOrder (string customerIdArg, string orderIdArg, string cartIdArg) {customerId = customerIdArg;
orderId = orderIdArg;
cartId = cartIdArg;}
public string AggregateId() { return cartId;}}}