/**
This code was generated by THE SPARKLING EVENTUAL CONSISTENT UNICORNS
Do not touch or risk the wrath of the ECUs
This Event was generated from DSL.json
*/
using Acme.Events;
namespace Acme.Events {public class CustomerPlacedOrder: Event {public string customerId {get;}
public string orderId {get;}public CustomerPlacedOrder (string customerIdArg, string orderIdArg) {customerId = customerIdArg;
orderId = orderIdArg;}
}}