/**
This code was generated by THE SPARKLING EVENTUAL CONSISTENT UNICORNS
Do not touch or risk the wrath of the ECUs
This Event was generated from DSL.json
*/using Acme.Event;
namespace Acme.Event.CustomerPlacedOrder {public class CustomerPlacedOrder: Event {public String customerId {get; private set;}
public String cartId {get; private set;}}}