/**
This code was generated by THE SPARKLING EVENTUAL CONSISTENT UNICORNS
Do not touch or risk the wrath of the ECUs
This Event was generated from DSL.json
*/
using Acme.Events;
namespace Acme.Events {public class ProductWasRemovedFromCart: Event {public string customerId {get; private set;}
public string cartId {get; private set;}}}